### ISSUE TITLE
can't set email on Create Issued Document Enity

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/openapi-fattureincloud#821]
POST /c/{company_id}/issued_documents

With the above endpoint, according with the docs

email: string

https://developers.fattureincloud.it/api-reference/#post-/c/-company_id-/issued_documents

we have to be able to set the email filed on the entity but if we do that this info is not predent in the issued document if we don't save the "entity" (client) on the backend, seems a bug.

Thaks

MM

**Comment by emajo** [comment]
Hi @Mattia-Marchiorato, we already discussed this topic several times in our github discussions ([here](https://github.com/fattureincloud/api/discussions/93) for example).

So, creating an issued document the fields email, phone and fax are ignored, but they are present on the documentation because under the hood they use the same model and to generate consistent classes for our SDKs we need them like that.

Thanks,
Emanuele.
