### ISSUE TITLE
nosense entity model on Create Issued Document

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/openapi-fattureincloud#830]
Hello,

on POST /c/{company_id}/issued_documents
there is an "entity" model that is related to clients in FIC but there is no way to bind this entity where we create an issued document with the client, this not make any sense and is a big problem.

Hope there is a solution

Thanks

MM

**Comment by emajo** [comment]
Hi @Mattia-Marchiorato, actually the entity model is related to both the client and supplier models so creating an issued document there needs to be a manual binding from the Client or Supplier model (depending on the document type) to the Entity that is needed by the IssuedDocument model.

Thanks,
Emanuele.

**Comment by Mattia-Marchiorato** [comment]
Hello @emajo,

can't see any reference about entity type on the API Reference,
There is only a "Type"
type: enum
EntityType: Entity type
Default: null Allowed: company┃person┃pa┃condo

But no difference between Client And Supplier, can you please be more explicit?

Thanks

MM

**Comment by valmoz** [comment]
Hi @Mattia-Marchiorato 
In our APIs, we always deal with "Entities", that are used to represent both Clients and Suppliers. You can check this fact on the Clients and Suppliers methods, which include "entities" in the path.

Since Clients and Suppliers differ for a subset of fields, while modeling the APIs in our OpenAPI Spec we preferred to manage them as two different models when possible to avoid ambiguities.
Unfortunately for issues related to the SDK generator it was not possible to indicate both Client or Supplier as acceptable types for the entity field in the Create Issued Document method, so we opted to manage them with the original "Entity" model that contains all the parameters accepted for Clients and Suppliers.

What we suggest, if you already have a client and you want to use it to populate the creation request, is to write a simple client2entity method that accepts the Client and returns the Entity, simply by mapping the fields of the client into the fields of the entity(the fields name should be the same for all fields). It should be also possible to marshal a Client into its JSON representation and unmarshal it to an Entity if preferred.

Thanks
Mauro

**Comment by valmoz** [comment]
Yes @Mattia-Marchiorato unfortunately we know some parts of our APIs can be confusing, let us know if we can further help you with this topic.

**Comment by Mattia-Marchiorato** [comment]
No thanks.
