### ISSUE TITLE
POST /c/{company_id}/issued_documents net_price issue invoice total to 0

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/openapi-fattureincloud#874]
Hello,

according to your doc https://developers.fattureincloud.it/api-reference#post-/c/-company_id-/issued_documents
net_price can be null, or better empty ''. In this case, when we set a gross_rice and the iva the api emit an invoice with 0 as total amount.

Step to recreate:
POST /c/{company_id}/issued_documents

Set 

```
net_price: ''
gross_price: 20
vat:{
  id: 0,
  value: 22
}
```

Thanks

MM

**Comment by emajo** [comment]
Hi @Mattia-Marchiorato, I don't get your point, it's correct that the net_price can be empty, because setting the `use_gross_prices` field to true the net will be calculated from gross and vat, if you don't specify that fiel, gross_price is ignored as explained [here](https://developers.fattureincloud.it/docs/guides/invoice-creation#five-step-five-items-list).

Thanks,
Emanuele.

**Comment by Mattia-Marchiorato** [comment]
Hello @emajo,

thanks, in the api-reference is not that clear that you have to set use_gross_prices to use gross_price, neither in the api error, with that field is workin.

Thanks

MM
